apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: infra
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # headless para StatefulSet
  selector:
    app: mongodb
