apiVersion: v1
kind: Service
metadata:
  name: source-router
  namespace: apis
spec:
  type: ClusterIP
  selector:
    app: source-router
  ports:
    - name: http
      port: 8075
      targetPort: 8075
