apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: infra
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      # Update after changing configmap.yaml so Kubernetes rolls the pods.
      annotations:
        checksum/fluent-bit-config: "9954899eb05989e9ce2378322c5210475cec4d068e3335dd2190c13d362e4dec"
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: cr.fluentbit.io/fluent/fluent-bit:3.0.0
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config