
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../configmap.yaml
  - ../../service.yaml
  - ../../deployment.yaml

# Reemplaza el comando manual: kubectl create secret generic mongodb-secret ...
# secretGenerator:
# - name: mongodb-secret
#   namespace: infra
#   envs:
#     - prod-mongodb.env
patches:
  - path: patch-resources.yaml 
generatorOptions:
  disableNameSuffixHash: true