apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../deployment-validator.yaml

nameSuffix: "-2" # Esto cambia el nombre a validate-worker-1 y validator-secret-1

# Leemos tu archivo .env local para generar el secreto
secretGenerator:
  - name: validator-secret
    namespace: apis
    envs:
      - worker-2.env

# Desactivamos el hash aleatorio al final del nombre del secreto
generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: validate-worker
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/instance
        value: "2"
      - op: replace
        path: /spec/selector/matchLabels/instance
        value: "2"
