apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-worker # Tiene que llamarse igual que en la base
  namespace: apis
spec:
  template:
    spec:
      containers:
      - name: worker
        # Kustomize inyectará estas variables automáticamente en la lista de 'env' de tu base
        env:
        - name: AI_PROVIDER
          value: "openrouter"
        - name: MODEL
          value: "mistralai/mistral-small-24b-instruct-2501"
        - name: API_URL
          value: "https://openrouter.ai/api/v1/chat/completions"
        - name: VALIDATOR_SERVICE_URL
          value: "http://validate-service-3.apis.svc.cluster.local:8070"
        - name: VALIDATOR_TYPE
          value: "3"
        - name: EVIDENCE_SEARCH_URL
          value: "http://evidence-search.apis.svc.cluster.local:8074"
        - name: EVIDENCE_SEARCH_USE_PREFERRED_DOMAINS
          value: "LOCAL"
        - name: EVIDENCE_SEARCH_PREFERRED_PROFILE_ID
          value: "default"
        
