apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-middleware.yaml
  - gateway-ingress.yaml
  - keycloak-ingress.yaml
  - frontend-ingress.yaml
  - frontend-middleware.yaml
  - tls-store.yaml
