apiVersion: v1
kind: Service
metadata:
  name: geth-miner
  namespace: blockchain
spec:
  type: ClusterIP
  selector:
    app: geth-miner
  ports:
    - name: p2p-tcp
      port: 30305
      targetPort: 30305
      protocol: TCP
    - name: p2p-udp
      port: 30305
      targetPort: 30305
      protocol: UDP
    - name: http
      port: 8557
      targetPort: 8557
      protocol: TCP