# ./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/namespaces.yaml
  - k8s/infra/zookeeper
  - k8s/infra/kafka
  - k8s/infra/mongodb
  - k8s/infra/ipfs
  - k8s/infra/fluent-bit
  - k8s/infra/frontend-logs
  - k8s/blockchain
  - k8s/apis/generate-asertions
  - k8s/apis/ipfs-fastapi
  - k8s/apis/news-chain
  - k8s/apis/validate-asertions
  - k8s/apis/news-handler
  - k8s/frontend