apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-asertions
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-asertions
  template:
    metadata:
      labels:
        app: generate-asertions
    spec:
      initContainers: 
        - name: wait-for-kafka
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |
              until nc -z kafka.infra.svc.cluster.local 9092; do
                echo "Esperando a Kafka..."
                sleep 2
              done
      containers:
      - name: generate-asertions
        image: generate-asertions
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8071
        envFrom:
        - configMapRef:
            name: generate-asertions-config
        - secretRef:               
            name: api-keys         
        env:
        - name: IPFS_API_ADD
          value: "http://ipfs-fastapi.apis.svc.cluster.local:8060/api/v0/add"
        - name: IPFS_API_CAT
          value: "http://ipfs-fastapi.apis.svc.cluster.local:8060/api/v0/cat"