apiVersion: v1
kind: Service
metadata:
  name: geth-rpc-endpoint
  namespace: blockchain
spec:
  type: ClusterIP
  selector:
    app: geth-rpc-endpoint
  ports:
    - name: http
      port: 8555
      targetPort: 8555
      protocol: TCP
    - name: ws
      port: 8556
      targetPort: 8556
      protocol: TCP
    - name: p2p-tcp
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: p2p-udp
      port: 30303
      targetPort: 30303
      protocol: UDP