
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: apis
spec:
  selector:
    app: admin
  ports:
  - protocol: TCP
    port: 8400        # Puerto expuesto del servicio
    targetPort: 8400  # Puerto al que apunta en el contenedor
  type: ClusterIP     # Solo visible dentro del clúster