resources:
  - ../../base

secretGenerator:
  - name: keycloak-admin-secret
    envs:
      - secrets.env
  - name: keycloak-db-secret
    envs:
      - secrets.env
  - name: keycloak-tls-secret
    files:
      - tls.crt
      - tls.key


generatorOptions:
  disableNameSuffixHash: true
namespace: infra