apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: infra
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0
          args: ["start"] 
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak"
            - name: KC_HOSTNAME
              value: "localhost" # O tu dominio real
            - name: KC_HOSTNAME_PORT
              value: "7443"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/opt/keycloak/conf/trustnews.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/opt/keycloak/conf/trustnews.key"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
            - name: KC_PROXY
              value: "reencrypt" # <--- Vital para Nginx(https) -> Keycloak(https)
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"  # <--- Esto permite que Keycloak responda a diferentes puertos
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: ADMIN_USER
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: ADMIN_PASSWORD
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: DB_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: DB_PASSWORD
            
          ports:
            - containerPort: 8443 # Puerto HTTPS por defecto en modo prod
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTPS 
          #     path: /auth/health/ready
          #     port: 8443  
          volumeMounts:
            - name: certs
              mountPath: "/opt/keycloak/conf/trustnews.crt"
              subPath: tls.crt
            - name: certs-key
              mountPath: "/opt/keycloak/conf/trustnews.key"
              subPath: tls.key
      volumes:
        - name: certs
          secret:
            secretName: keycloak-tls-secret
        - name: certs-key
          secret:
            secretName: keycloak-tls-secret
