apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: infra
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak
          imagePullPolicy: IfNotPresent
          args:
            - start
            - --optimized
            - --http-enabled=true # Habilita explícitamente el puerto HTTP
          env:
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak"
            - name: KC_HOSTNAME_URL
              value: "https://localhost:7443/auth"       # Fuerza HTTPS globalmente
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://localhost:7443/auth"       # Fuerza HTTPS para la consola admin


            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"                   # Vital para Keycloak 24+
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: ADMIN_USER
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: ADMIN_PASSWORD
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: DB_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: DB_PASSWORD
          ports:
            - name: http
              containerPort: 8080 # Puerto estándar HTTP de Keycloak
          readinessProbe:
            httpGet:
              scheme: HTTP # Cambiado de HTTPS a HTTP
              path: /auth/health/ready
              port: 8080
          # Puedes comentar o quitar los volumes de TLS si ya no quieres 
          # que KC gestione certificados internamente (edge mode).