apiVersion: v1
kind: Service
metadata:
  name: validate-service # Kustomize le añadirá el "-1" al final
  namespace: apis
spec:
  selector:
    app: validate-worker
    instance: "1" # <- Esta es la clave para que apunte solo a este worker
  ports:
    - protocol: TCP
      port: 8070           # El puerto del servicio en el clúster
      targetPort: 8070   # El mismo puerto que añadiste en tu deployment base