apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: blockchain
---
apiVersion: v1
kind: Namespace
metadata:
  name: apis
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
