apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-worker # Tiene que coincidir con el nombre de la base
  namespace: apis
spec:
  # En producción podríamos querer 2 réplicas por si una cae, 
  # pero si tu worker no soporta concurrencia, déjalo en 1.
  replicas: 1 
  template:
    spec:
      containers:
      - name: worker
        # Definimos cuánta CPU y RAM reserva y cuál es su límite máximo
        env:
        - name: AI_PROVIDER
          value: "openrouter"
        - name: MODEL
          value: "mistralai/mistral-small-24b-instruct-2501"
        - name: API_URL
          value: "https://openrouter.ai/api/v1/chat/completions"
        - name: VALIDATOR_SERVICE_URL
          value: "http://validate-service-3.apis.svc.cluster.local:8070"
        - name: VALIDATOR_TYPE
          value: "3"
        - name: EVIDENCE_SEARCH_URL
          value: "http://evidence-search.apis.svc.cluster.local:8074"
        - name: EVIDENCE_SEARCH_USE_PREFERRED_DOMAINS
          value: "LOCAL"
        - name: EVIDENCE_SEARCH_PREFERRED_PROFILE_ID
          value: "default"
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"