# k8s/blockchain-pvcs.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpc-data-geth-rpc-endpoint-0
  namespace: blockchain
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miner-data-geth-miner-0
  namespace: blockchain
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi