# LOKI (Versión estable y compatible)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        # Usamos la 3.0.0 que es robusta y compatible con los dashboards actuales
        image: grafana/loki:3.0.0
        ports:
        - containerPort: 3100
        # Loki es intensivo en disco/memoria, conviene darle un respiro
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        # Argumento básico para que funcione sin configuración compleja de S3
        args:
          - "-config.file=/etc/loki/local-config.yaml"