apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-worker # Tiene que llamarse igual que en la base
  namespace: apis
spec:
  template:
    spec:
      containers:
      - name: worker
        # Kustomize inyectará estas variables automáticamente en la lista de 'env' de tu base
        env:
        - name: AI_PROVIDER
          value: "grok"
        - name: MODEL
          value: "llama-3.1-8b-instant"
        - name: API_URL
          value: "https://api.groq.com/openai/v1/chat/completions"