
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../configmap.yaml
  - ../../service.yaml
  - ../../deployment.yaml

generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:

- name: news-handler-secrets
  namespace: apis
  envs:
    - news-handler.env
namespace: apis