apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-frontend-host.yaml
  - path: patch-gateway-host.yaml
  - path: patch-keycloak-host.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: trustnews-origin-tls
    namespace: kube-system
    type: kubernetes.io/tls
    files:
      - tls.crt=../../../../web_classic/certs/fullchain.pem
      - tls.key=../../../../web_classic/certs/privkey.pem
