apiVersion: v1
kind: ConfigMap
metadata:
  name: news-handler-config
  namespace: apis
data:
  # --- Kafka ---
  KAFKA_BROKER: "kafka.infra.svc.cluster.local:9092"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  KAFKA_MECHANISM: "PLAIN"
  
  # --- Tópicos ---
  TOPIC_REQUESTS_GENERATE: "fake_news_requests_generate"
  TOPIC_REQUESTS_IPFS: "fake_news_requests_ipfs"
  TOPIC_REQUESTS_BLOCKCHAIN: "fake_news_requests_blockchain"
  TOPIC_REQUESTS_VALIDATE: "fake_news_requests_validate"
  TOPIC_RESPONSES: "fake_news_responses"
  TOPIC_LIGHT_VALIDATION_REQUESTS: "fake_news_requests_light_validation"
  TOPIC_LIGHT_VALIDATION_RESPONSES: "fake_news_responses"

  # --- MongoDB ---
  MONGO_DBNAME: "newsdb"
  MONGO_COLLECTION: "news"
  MONGO_EVENTS_COLLECTION: "events"
  MONGO_VALIDATIONS_COLLECTION: "validations"
  MONGO_CONFIG_COLLECTION: "config"
  
  # --- App Config ---
  MAX_WORKERS: "3"
  IMPORT_URL_TIMEOUT_SECONDS: "10"
  IMPORT_URL_MAX_REDIRECTS: "3"
  IMPORT_URL_MAX_BYTES: "2097152"

  
  # --- URLs Internas ---
  IPFS_FASTAPI_URL: "http://ipfs-fastapi.apis.svc.cluster.local:8060"
  NEWS_CHAIN_URL: "http://news-chain.apis.svc.cluster.local:8073"
  ADMIN_URL: "http://admin-service.apis.svc.cluster.local:8400"