server {
    listen 80;
    server_name localhost;
    # 1. Cambiamos el puerto al NodePort de Kubernetes
    return 301 https://$host:7443$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    # 2. Nombres estándar de Kubernetes para secretos TLS
    ssl_certificate     /etc/nginx/certs/tls.crt;
    ssl_certificate_key /etc/nginx/certs/tls.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;


    # location /auth/admin/ {
    #     deny all;
    # }
    
    
    # location /auth/realms/master/ {
    #     deny all;
    # }



    location /auth/ {
        # Apuntamos al nuevo puerto del Service
        proxy_pass http://keycloak.infra.svc.cluster.local:8080; 
        
        # Cabeceras esenciales para Keycloak en modo 'edge'
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Indica a Keycloak que el protocolo externo es HTTPS
        proxy_set_header X-Forwarded-Proto https;
        
        # Indica a Keycloak el Host y el Puerto externos (importante para redirects)
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 7443;

        # Optimización para la consola de administración de Keycloak
        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;

        # Como ahora es HTTP interno, no necesitamos proxy_ssl_verify
        proxy_intercept_errors off;
    }



    location /backend/ {
        proxy_pass http://gateway.apis.svc.cluster.local:8500/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Esto le dice a FastAPI que genere las URLs de Swagger empezando por /backend
        proxy_set_header X-Forwarded-Prefix /backend;
    }
    
    location / {
        try_files $uri /index.html;
    }
}