apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: infra
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.6.1
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: zookeeper-config
          volumeMounts:
            - name: zk-storage
              mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zk-storage
        namespace: infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi