apiVersion: v1
kind: ConfigMap
metadata:
  name: validate-common-config
  namespace: apis
data:
  # AI_PROVIDER: "openrouter"
  # MODEL: "arcee-ai/trinity-large-preview:free"
  # API_URL: "https://openrouter.ai/api/v1/chat/completions"

  

  VALIDATOR_TYPE: "1"
  EVIDENCE_SEARCH_URL: "http://evidence-search.apis.svc.cluster.local:8074"
  EVIDENCE_SEARCH_USE_PREFERRED_DOMAINS: "NONE"
  EVIDENCE_SEARCH_PREFERRED_PROFILE_ID: "default"

  LLM_MEMORY_VALIDATION_PROMPT: |
    Actúa como validador factual prudente.
    Valida la aserción usando tu conocimiento general y razonamiento lógico.
    No inventes información.
    Si no puedes verificarlo con suficiente seguridad, devuelve UNKNOWN.
    Explica porque has tomado su decision de forma breve y objetiva.
    Devuelve exclusivamente JSON válido:
    {
      "resultado": "TRUE | FALSE | UNKNOWN",
      "descripcion": "Justificación breve y objetiva"
    }

  LLM_SEARCH_VALIDATION_PROMPT: |
    Actúa como validador factual con búsqueda online.
    Busca evidencias actuales en Internet cuando sea necesario.
    Prioriza fuentes oficiales, agencias de noticias y fuentes reputadas.
    Explica porque has tomado su decision de forma breve y objetiva citando las fuentes.
    Devuelve exclusivamente JSON válido:
    {
      "resultado": "TRUE | FALSE | UNKNOWN",
      "descripcion": "Justificación breve y objetiva",
      "sources": [
        {
          "url": "string",
          "title": "string",
          "reason": "string"
        }
      ]
    }

  RAG_EVIDENCE_VALIDATION_PROMPT: |
    Actúa como validador factual estricto.
    Debes validar la aserción usando exclusivamente las evidencias proporcionadas.
    No uses conocimiento interno salvo razonamiento lógico básico.
    No inventes fuentes.
    No accedas a URLs externas.
    Si las evidencias no son suficientes, devuelve UNKNOWN.
    Explica porque has tomado su decision de forma breve y objetiva citando las fuentes.
    Devuelve exclusivamente JSON válido:
    {
      "resultado": "TRUE | FALSE | UNKNOWN",
      "descripcion": "Justificación breve y objetiva",
      "confidence": "HIGH | MEDIUM | LOW",
      "evidence_used": [
        {
          "source_id": "string",
          "url": "string",
          "supports": true,
          "reason": "string"
        }
      ]
    }

  # Kafka (Namespace infra)
  KAFKA_BOOTSTRAP: "kafka.infra.svc.cluster.local:9092"
  TOPIC_RESPONSES: "fake_news_responses"
  TOPIC_LIGHT_VALIDATION_REQUESTS: "fake_news_requests_light_validation"

  # Blockchain (Namespace blockchain)
  RPC_URL: "http://geth-rpc-endpoint.blockchain.svc.cluster.local:8555"
  CONTRACT_ADDRESS: "0x928E691aF55fF3530127BcA7E06e35f3F9a77CF6"
  CONTRACT_ABI_PATH: "/app/smart-contracts/artifacts/contracts/TrustNews.sol/TrustNews.json"

  # IPFS (Namespace apis)
  IPFS_API_URL: "http://ipfs-fastapi.apis.svc.cluster.local:8060"
  LOG_LEVEL: "INFO"
  TEMPERATURE: "0.0"