apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: apis
data:
  # URLs de los Microservicios
  NEWS_HANDLER_URL: "http://news-handler.apis.svc.cluster.local:8072"
  NEWS_CHAIN_URL: "http://news-chain.apis.svc.cluster.local:8073"
  IPFS_API_URL: "http://ipfs-fastapi.apis.svc.cluster.local:8060"
  GENERATE_ASSERTIONS_URL: "http://generate-asertions.apis.svc.cluster.local:8071"
  
  # Configuración de Keycloak
  KEYCLOAK_REALM: "TrustNews"
  KEYCLOAK_ISSUER_URL: "https://localhost:7443/auth/realms/TrustNews"
  KEYCLOAK_JWKS_URL: "http://keycloak.infra.svc.cluster.local:8080/auth/realms/TrustNews/protocol/openid-connect/certs"

  # La documentación interactiva solo se mantiene en local.
  GATEWAY_API_DOCS_ENABLED: "true"
