apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: apis
data:
  # URLs de los Microservicios
  NEWS_HANDLER_URL: "http://news-handler.apis.svc.cluster.local:8072"
  NEWS_CHAIN_URL: "http://news-chain.apis.svc.cluster.local:8073"
  IPFS_API_URL: "http://ipfs-fastapi.apis.svc.cluster.local:8060"
  GENERATE_ASSERTIONS_URL: "http://generate-asertions.apis.svc.cluster.local:8071"
  
  # Configuración de Keycloak
  KEYCLOAK_SERVER_INNER_URL: "https://keycloak.infra.svc.cluster.local:8443/auth"
  KEYCLOAK_SERVER_URL:  https://localhost:7443/auth
  KEYCLOAK_SERVER_HOSTNAME : "https://localhost"
  KEYCLOAK_SERVER_PORT : "7443"
  KEYCLOAK_SERVER_PATH : "auth"
  
  
  KEYCLOAK_REALM: "TrustNews"
  KEYCLOAK_CLIENT_ID: "TrustNewsWeb"