
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: apis
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8500        # Puerto expuesto del servicio
    targetPort: 8500  # Puerto al que apunta en el contenedor
  type: ClusterIP     # Solo visible dentro del clúster