apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: tavily-secret
    namespace: apis
    envs:
      - tavily.env

namespace: apis
