apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-worker-1
  namespace: apis
spec:
  replicas: 1 # Cada deployment es un trabajador único
  selector:
    matchLabels:
      app: validate-worker
      instance: "1"
  template:
    metadata:
      labels:
        app: validate-worker
        instance: "1"
    spec:
      initContainers: # SECCIÓN A AÑADIR (Corre antes de todo)
        - name: wait-for-kafka
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |
              until nc -z kafka.infra.svc.cluster.local 9092; do
                echo "Esperando a Kafka..."
                sleep 2
              done
      containers:
      - name: worker
        #image: tfm-validate-asertions-worker_1:latest
        image: validate-asertions
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: validate-common-config
        env:
        # Sobreescribimos con los valores únicos de este validador
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: validator-1-secret
              key: PRIVATE_KEY
        - name: ACCOUNT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: validator-1-secret
              key: ACCOUNT_ADDRESS
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: validator-1-secret
              key: API_KEY
        - name: VALIDATOR_CATEGORIES
          value: "[1,2,3,4,5,6,7,8,9,10]"
        volumeMounts:
        - name: abi-volume
          mountPath: /app/smart-contracts/artifacts/contracts/TrustNews.sol/TrustNews.json
          subPath: TrustNews.json
      volumes:
      - name: abi-volume
        configMap:
          name: news-chain-contract # Reutilizamos el ConfigMap que ya tiene el JSON
          items:
          - key: "TrustNews.json"
            path: "TrustNews.json"