apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

secretGenerator:
  - name: mongo-express-secret
    namespace: infra
    envs:
      - mongo-express.env

generatorOptions:
  disableNameSuffixHash: true

namespace: infra
